---
# roles/prometheus/defaults/main.yml
prometheus_version: "2.52.0"
prometheus_port: 9090
prometheus_user: "prometheus"
prometheus_config_dir: "/etc/prometheus"
prometheus_data_dir: "/var/lib/prometheus"
prometheus_install_dir: "/usr/local/bin"

# Cibles à scraper (modifiable via group_vars ou host_vars)
prometheus_scrape_targets:
  - job_name: "node-monitoring"
    targets:
      - "localhost:9100"
  - job_name: "node-target"
    targets:
      - "192.168.56.20:9100"
