# =============================================================================
# TP InfluxDB v3 — Vagrantfile
# Box     : ubuntu/jammy64 (Ubuntu 22.04 LTS)
# RAM     : 8192 Mo | vCPU : 2
# =============================================================================

Vagrant.configure("2") do |config|

  config.vm.box              = "ubuntu/jammy64"
  config.vm.box_check_update = false

  config.vm.define "influxdb" do |inf|
    inf.vm.hostname = "influxdb-lab"
    inf.vm.network "private_network", ip: "192.168.56.10"

    inf.vm.network "forwarded_port", guest: 8086, host: 8086
    inf.vm.network "forwarded_port", guest: 3000, host: 3000

    inf.vm.provider "virtualbox" do |vb|
      vb.name         = "tp-influxdb-v3"
      vb.cpus         = 2
      vb.memory       = 8192
      vb.linked_clone = true
    end

    # Copie ansible.cfg vers ~/.ansible.cfg avant le lancement
    inf.vm.provision "shell", inline: <<-SHELL
      cp /vagrant/ansible.cfg /home/vagrant/.ansible.cfg
      chmod 600 /home/vagrant/.ansible.cfg
      chown vagrant:vagrant /home/vagrant/.ansible.cfg
      echo "ansible.cfg copié vers ~/.ansible.cfg"
      cat /home/vagrant/.ansible.cfg
    SHELL

    inf.vm.provision "ansible_local" do |ansible|
      ansible.playbook           = "ansible/playbook.yml"
      ansible.provisioning_path  = "/vagrant"
      ansible.install            = true
      ansible.compatibility_mode = "2.0"
      ansible.extra_vars         = {
        influxdb_bind_address:  "0.0.0.0",
        influxdb_port:          8086,
        influxdb_data_dir:      "/var/lib/influxdb3",
        influxdb_config_dir:    "/etc/influxdb3",
        influxdb_db_name:       "usine_analytics",
        influxdb_db_historique: "usine_historique_5ans",
        influxdb_token:         "REMPLACER_APRES_GENERATION",
        grafana_port:           3000,
        grafana_admin_user:     "admin",
        grafana_admin_password: "admin",
        influxdb_python_client: "influxdb3-python"
      }
    end
  end

end
