; Inventaire TP Observabilité Sécurisée
; Groupes par rôle/zone pour cibler les playbooks par couche

[prod]
web-prod ansible_host=10.0.20.20

[router]
fw-router ansible_host=10.0.20.1

[admin]
supervision ansible_host=10.0.10.5

[all:vars]
ansible_connection=local
ansible_python_interpreter=/usr/bin/python3

; Variables de zone réutilisées dans les rôles (matrice de flux)
[prod:vars]
zone_name=DMZ_PRODUCTION

[admin:vars]
zone_name=DMZ_ADMIN
